# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP app to Azure Web App - firstApp20

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: nuget restore
        working-directory: ./ # Change this to the correct path to your solution file

      - name: Build solution
        run: msbuild /nologo /verbosity:m /t:Build /p:Configuration=Release
        working-directory: ./ # Update this as well

      - name: Publish to folder
        run: msbuild /nologo /verbosity:m /t:Publish /p:Configuration=Release /p:WebPublishMethod=FileSystem /p:publishUrl="\published\"
        working-directory: ./ # Update this too

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: '/published/**'
          if-no-files-found: error

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ASP-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_391E2C98A7CF47989CE761E98CB82BFD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_641DD25F6DC349DD946346FA2AFE29B0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DCE8506D2B6B41DBA945303E9BDDE94D }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'firstApp20'
          slot-name: 'Production'
          package: .
